In [2]:
import numpy as np
from tensorflow import keras
import tensorflow as tf
import tensorflow.keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, BatchNormalization, MaxPool2D, Flatten, Dense, Dropout
import cv2 as cv
import os
import pickle
import time
import random
import matplotlib.pyplot as plt



In [3]:
scans = np.load("scans.npy",allow_pickle=True)
labels = np.load("labels.npy")
print(scans)


[[[[0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   ...
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]]

  [[0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   ...
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]]

  [[0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   ...
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]]

  ...

  [[0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   ...
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]]

  [[0.00392157 0.00392157 0.00392157]
   [0.0

In [6]:
Model = Sequential([Conv2D(filters=32,  kernel_size=(3,3), activation="relu", input_shape=scans.shape[1:]),
                    BatchNormalization(),
                    MaxPool2D(2,2),
                    Dropout(0.2),
                 
                    Conv2D(filters=16,  kernel_size=(3,3), activation="relu"),
                    BatchNormalization(),
                    MaxPool2D(3,3),
                    Dropout(0.2),
    
                    Flatten(),
    
                    Dense(units=8, activation="relu"),
                    BatchNormalization(),
                    Dropout(0.3),
                    
                                        
                    Dense(units=4, activation="relu"),
                    BatchNormalization(),
                    Dropout(0.5),
                    
                    Dense(2, activation='softmax'),
])

Model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

Model.summary()


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 198, 198, 32)      896       
_________________________________________________________________
batch_normalization_4 (Batch (None, 198, 198, 32)      128       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 99, 99, 32)        0         
_________________________________________________________________
dropout_4 (Dropout)          (None, 99, 99, 32)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 97, 97, 16)        4624      
_________________________________________________________________
batch_normalization_5 (Batch (None, 97, 97, 16)        64        
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 32, 32, 16)       

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(scans, labels, test_size=0.33)
Model.fit(X_train, y_train, epochs = 200)

Epoch 1/200
4/4 [==============================] - 4s 468ms/step - loss: 1.0378 - accuracy: 0.4970
Epoch 2/200
4/4 [==============================] - 2s 514ms/step - loss: 1.0151 - accuracy: 0.5226
Epoch 3/200
4/4 [==============================] - 2s 454ms/step - loss: 1.1131 - accuracy: 0.5701
Epoch 4/200
4/4 [==============================] - 2s 459ms/step - loss: 0.9502 - accuracy: 0.5372
Epoch 5/200
4/4 [==============================] - 2s 442ms/step - loss: 0.6781 - accuracy: 0.6634
Epoch 6/200
4/4 [==============================] - 2s 448ms/step - loss: 0.5869 - accuracy: 0.7058
Epoch 7/200
4/4 [==============================] - 2s 438ms/step - loss: 0.6794 - accuracy: 0.6089
Epoch 8/200
4/4 [==============================] - 2s 447ms/step - loss: 0.5916 - accuracy: 0.6798
Epoch 9/200
4/4 [==============================] - 2s 460ms/step - loss: 0.5769 - accuracy: 0.7573
Epoch 10/200
4/4 [==============================] - 2s 442ms/step - loss: 0.5617 - accuracy: 0.6829
Epoch 11/

4/4 [==============================] - 2s 534ms/step - loss: 0.2930 - accuracy: 0.9029
Epoch 84/200
4/4 [==============================] - 2s 472ms/step - loss: 0.2458 - accuracy: 0.9123
Epoch 85/200
4/4 [==============================] - 2s 455ms/step - loss: 0.2502 - accuracy: 0.9153
Epoch 86/200
4/4 [==============================] - 2s 454ms/step - loss: 0.3088 - accuracy: 0.8935
Epoch 87/200
4/4 [==============================] - 2s 485ms/step - loss: 0.3088 - accuracy: 0.8782
Epoch 88/200
4/4 [==============================] - 2s 481ms/step - loss: 0.3194 - accuracy: 0.8759
Epoch 89/200
4/4 [==============================] - 2s 455ms/step - loss: 0.2855 - accuracy: 0.9008
Epoch 90/200
4/4 [==============================] - 2s 467ms/step - loss: 0.2537 - accuracy: 0.9040
Epoch 91/200
4/4 [==============================] - 2s 483ms/step - loss: 0.3002 - accuracy: 0.8719
Epoch 92/200
4/4 [==============================] - 2s 577ms/step - loss: 0.3028 - accuracy: 0.8595
Epoch 93/200


4/4 [==============================] - 2s 457ms/step - loss: 0.3105 - accuracy: 0.8782
Epoch 165/200
4/4 [==============================] - 2s 438ms/step - loss: 0.3579 - accuracy: 0.8533
Epoch 166/200
4/4 [==============================] - 2s 448ms/step - loss: 0.2529 - accuracy: 0.9185
Epoch 167/200
4/4 [==============================] - 2s 447ms/step - loss: 0.3114 - accuracy: 0.8780
Epoch 168/200
4/4 [==============================] - 2s 451ms/step - loss: 0.2665 - accuracy: 0.9101
Epoch 169/200
4/4 [==============================] - 2s 448ms/step - loss: 0.2520 - accuracy: 0.8948
Epoch 170/200
4/4 [==============================] - 2s 437ms/step - loss: 0.3066 - accuracy: 0.8978
Epoch 171/200
4/4 [==============================] - 2s 447ms/step - loss: 0.2585 - accuracy: 0.8998
Epoch 172/200
4/4 [==============================] - 2s 447ms/step - loss: 0.2522 - accuracy: 0.9277
Epoch 173/200
4/4 [==============================] - 2s 450ms/step - loss: 0.2730 - accuracy: 0.8843
Epoc

In [18]:
Model.save("final_79.h5")
model = keras.models.load_model("final_79.h5")

In [19]:
def prepare(pic):
    pic = pic.reshape(-1, 200, 200,3)
    return pic/255




In [20]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator,load_img
categories= ["N","S"]
def classify(image):
    try:
        frame = cv.imread(image)
        frame = prepare(frame)
    except:
        frame = image.reshape(-1,200,200,3)
    predictions = model.predict([frame])
    return predictions[0]
    


In [21]:
image = X_test[9]
print(image.shape, y_test[9])
 
def predict(image):
    c = classify(image)
    p=0
    for a in c:
        if a > p: p = a
    return categories[(list(c).index(p))]
    

(200, 200, 3) [0. 1.]


In [22]:
predict(image)

'S'

In [23]:
import numpy
cvscores = []
scores = model.evaluate(X_test, y_test, verbose=1)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
cvscores.append(scores[1] * 100)
print("%.2f%% (+/- %.2f%%)" % (numpy.mean(cvscores), numpy.std(cvscores)))


2/2 [==============================] - 0s 76ms/step - loss: 0.4835 - accuracy: 0.7959
accuracy: 79.59%
79.59% (+/- 0.00%)
